### ISSUE TITLE
Cannot Start Node

### ISSUE THREAD

**Issue by thiensubs** [srveit/mechanize-js#9]
When i start node your project: node bin/get_page.js
and get errrors bellow:
/home/thiensubs-linux/Documents/mechanize-js/node_modules/libxmljs/node_modules/bindings/bindings.js:79
        throw e
              ^
Error: /home/thiensubs-linux/Documents/mechanize-js/node_modules/libxmljs/build/Release/xmljs.node: undefined symbol: _ZN2v82V837AdjustAmountOfExternalAllocatedMemoryEl
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at bindings (/home/thiensubs-linux/Documents/mechanize-js/node_modules/libxmljs/node_modules/bindings/bindings.js:74:15)
    at Object.<anonymous> (/home/thiensubs-linux/Documents/mechanize-js/node_modules/libxmljs/lib/bindings.js:1:99)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)

**Comment by srveit** [comment]
I need more information. Add the version of node and the node modules:

```
node -v
npm ls
```

Also make sure you perform `npm install` before running the samples.

**Comment by thiensubs** [comment]
node -v : v0.12.2
npm ls:
├── cookiejar@1.3.0
├─┬ jasmine-node@1.10.1
│ ├── coffee-script@1.9.1
│ ├─┬ gaze@0.3.4
│ │ ├─┬ fileset@0.1.5
│ │ │ └─┬ glob@3.2.11
│ │ │   ├── inherits@2.0.1
│ │ │   └─┬ minimatch@0.3.0
│ │ │     ├── lru-cache@2.5.0
│ │ │     └── sigmund@1.0.0
│ │ └─┬ minimatch@0.2.14
│ │   ├── lru-cache@2.5.0
│ │   └── sigmund@1.0.0
│ ├── jasmine-reporters@2.0.5
│ ├── mkdirp@0.3.5
│ ├── requirejs@2.1.17
│ ├── underscore@1.8.3
│ └── walkdir@0.0.8
├─┬ libxmljs@0.8.1
│ └── bindings@1.0.0
├── mime@1.2.9
├─┬ nodelint@0.6.2
│ └── file@0.2.2
├─┬ request@2.21.0
│ ├── aws-sign@0.3.0
│ ├── cookie-jar@0.3.0
│ ├── forever-agent@0.5.2
│ ├─┬ form-data@0.0.8
│ │ ├── async@0.2.10
│ │ └─┬ combined-stream@0.0.7
│ │   └── delayed-stream@0.0.5
│ ├─┬ hawk@0.13.1
│ │ ├─┬ boom@0.4.2
│ │ │ └── hoek@0.9.1
│ │ ├── cryptiles@0.2.2
│ │ ├── hoek@0.8.5
│ │ └─┬ sntp@0.2.4
│ │   └── hoek@0.9.1
│ ├─┬ http-signature@0.9.11
│ │ ├── asn1@0.1.11
│ │ ├── assert-plus@0.1.2
│ │ └── ctype@0.5.2
│ ├── json-stringify-safe@4.0.0
│ ├── node-uuid@1.4.3
│ ├── oauth-sign@0.3.0
│ ├── qs@0.6.6
│ └── tunnel-agent@0.3.0
└── should@1.2.2
i was npm install, but i got message bellow:
npm WARN package.json cookiejar@1.3.0 No repository field.
Thanks.

**Comment by srveit** [comment]
I haven't upgraded to node 0.12 yet.

**Comment by mkormendy** [comment]
Is this closed or still an issue?

**Comment by srveit** [comment]
This is fixed in 1.0.1
